# This is a basic workflow to help you get started with Actions

name: Stage (blog.containerize.com)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'content/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # Step 2 - Sets up the latest version of Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'


    # Step 4 - Builds the site using the latest version of Hugo
    - name: Build
      run: hugo --config "./config/config-prod.yml" --minify --environment production


    # Deploys built website to S3
    - name: Deploy to S3
      run: hugo --config "./config/config-prod.yml" deploy --target "production" --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
        
    # Invalidate Cloudfront Home Page
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_PROD }}
          PATHS: /* /index.html
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
